spring:
  datasource:
    password: ${DB_PASS}
    username: ${DB_USER}
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
io:
  betterbanking:
    integration:
      url-base: http://localhost:8080